### ISSUE TITLE
Better error reporting for "no merger" complaints

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#143]
### Overview

Per #135, the output of a "no merger for multiple {rule} complaints..." complaint is shown as an Error with a full stack. Although this is an error in tslint-to-eslint-config, that call stack existing is kind of misleading. It's really just that we're missing a merger and someone should add it in.

#### Actual Behavior

```
no-eval threw an error during conversion: Error: No merger for multiple output no-eval rule configurations.
    at exports.convertRules (...\npm-cache_npx\14132\node_modules\tslint-to-eslint-config\src\rules\convertRules.js:37:67)
    at exports.convertConfig (...\npm-cache_npx\14132\node_modules\tslint-to-eslint-config\src\conversion\convertConfig.js:15:48)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
no-arg threw an error during conversion: Error: No merger for multiple output no-caller rule configurations.
    at exports.convertRules (...\npm-cache_npx\14132\node_modules\tslint-to-eslint-config\src\rules\convertRules.js:37:67)
at exports.convertConfig (...\npm-cache_npx\14132\node_modules\tslint-to-eslint-config\src\conversion\convertConfig.js:15:48)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

#### Expected Behavior

How about a nice message saying something like:

```
Error: multiple output no-eval ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this. Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=bug_report.md!
```

Thoughts, @joeyj-msft? I'll mark this as `good first issue` and `accepting prs` if you like this general approach.

**Comment by joeyj-msft** [comment]
Should we also output the contents of the conflicting rules? That way users could unblock themselves while they wait for an issue to be fixed :)
