### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by kristojorg** [typescript-eslint/tslint-to-eslint-config#263]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.11
-   ESLint version: 6.6.0
-   Node version: v11.10.1

#### Actual Behavior

I run the `npx` command and get the following output:
```
❌ 1 error running tslint-to-eslint: ❌
TypeError: Object.fromEntries is not a function
    at Object.exports.withKeysSorted (/Users/ksj/d/circulation-patron-web/node_modules/tslint-to-eslint-config/src/creation/formatting/formatters/withKeysSorted.js:4:19)
    at exports.formatJsOutput (/Users/ksj/d/circulation-patron-web/node_modules/tslint-to-eslint-config/src/creation/formatting/formatters/formatJsOutput.js:6:64)
    at Object.exports.formatOutput (/Users/ksj/d/circulation-patron-web/node_modules/tslint-to-eslint-config/src/creation/formatting/formatOutput.js:9:12)
    at exports.writeConversionResults (/Users/ksj/d/circulation-patron-web/node_modules/tslint-to-eslint-config/src/creation/writeConversionResults.js:27:79)
    at exports.convertConfig (/Users/ksj/d/circulation-patron-web/node_modules/tslint-to-eslint-config/src/conversion/convertConfig.js:22:47)
```

#### Expected Behavior

No error 

#### Reproduction

Here is the repo:
https://github.com/NYPL-Simplified/circulation-patron-web

**Comment by kristojorg** [comment]
For anyone out there I solved this by switching to an updated version of node!
