### ISSUE TITLE
TypeError: rule.ruleArguments is not iterable

### ISSUE THREAD

**Issue by HunSpeedi** [typescript-eslint/tslint-to-eslint-config#581]
### 🐛 Bug Report

-   ESLint version: ^7.0.0
-   Node version: v12.13.1

#### Actual Behavior
When i try to run the command: npx tslint-to-eslint-config i get the following error message:

```console
$ npx tslint-to-eslint-config
npx: installed 56 in 8.341s
❌ 1 error running tslint-to-eslint: ❌
  TypeError: rule.ruleArguments is not iterable
    at formatConvertedRule (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\creation\formatConvertedRules.js:18:39)
    at Object.exports.formatConvertedRules (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\creation\formatConvertedRules.js:8:28)
    at exports.writeConversionResults (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\creation\writeConversionResults.js:26:39)
    at exports.convertConfig (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\conversion\convertConfig.js:19:47)
    at async tryConvertConfig (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\cli\runCli.js:44:18)
    at async Object.exports.runCli (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\cli\runCli.js:32:24)
    at async Object.exports.main (C:\Users\Lorand\AppData\Roaming\npm-cache\_npx\19572\node_modules\tslint-to-eslint-config\src\cli\main.js:127:30)
```

#### Expected Behavior

Run without error.

#### Reproduction

**tsconfig.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
**package.json**
```
{
  "name": "movilitas.mobile-3.0",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "cypress:open": "cypress open",
    "cypress:run": "wait-on http://localhost:8100/ & cypress run --browser chrome --headless"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@auth0/angular-jwt": "^3.0.1",
    "@capacitor/android": "^2.1.0",
    "@capacitor/core": "^2.1.0",
    "@capacitor/ios": "^2.1.0",
    "@ionic-native/app-version": "^5.25.0",
    "@ionic-native/barcode-scanner": "^5.25.0",
    "@ionic-native/call-number": "^5.25.0",
    "@ionic-native/core": "^5.25.0",
    "@ionic-native/native-audio": "^5.25.0",
    "@ionic-native/splash-screen": "^5.25.0",
    "@ionic-native/status-bar": "^5.25.0",
    "@ionic/angular": "^5.1.0",
    "@ionic/pwa-elements": "^1.5.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "call-number": "^1.0.1",
    "com-darryncampbell-cordova-plugin-intent": "^2.0.0",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "core-js": "^3.6.5",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "rxjs": "^6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.26",
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular-devkit/core": "^8.3.26",
    "@angular-devkit/schematics": "^8.3.26",
    "@angular/cli": "^8.3.26",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "^2.1.0",
    "@ionic/angular-toolkit": "^2.2.0",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^12.12.38",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "codelyzer": "^5.2.2",
    "cypress": "^4.5.0",
    "eslint": "^7.0.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.20.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.4",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "wait-on": "^5.0.0"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "mx.ferreyra.callnumber": {},
      "com-darryncampbell-cordova-plugin-intent": {},
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-app-version": {}
    }
  }
}
```

**Comment by JoshuaKGoldberg** [comment]
Thanks for the bug report @HunSpeedi! Could you please post the contents of your **tslint.json** file? We can't do much on our end to reproduce this without knowing which TSLint rules you have enabled.

**Comment by HunSpeedi** [comment]
Oh, so sorry my bad, here it is:
tslint.json
`{
  "extends": "tslint:recommended",
  "rulesDirectory": [
    "codelyzer"
  ],
  "rules": {
    "array-type": false,
    "arrow-parens": false,
    "deprecation": {
      "severity": "warn"
    },
    "import-blacklist": [
      true,
      "rxjs/Rx"
    ],
    "interface-name": false,
    "max-classes-per-file": false,
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      {
        "order": [
          "static-field",
          "instance-field",
          "static-method",
          "instance-method"
        ]
      }
    ],
    "no-consecutive-blank-lines": false,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-empty": false,
    "no-inferrable-types": [
      true,
      "ignore-params"
    ],
    "no-non-null-assertion": true,
    "no-redundant-jsdoc": true,
    "no-switch-case-fall-through": true,
    "no-use-before-declare": true,
    "no-var-requires": false,
    "object-literal-key-quotes": [
      true,
      "as-needed"
    ],
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "quotemark": [
      true,
      "single"
    ],
    "trailing-comma": false,
    "no-output-on-prefix": true,
    "no-inputs-metadata-property": true,
    "no-host-metadata-property": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-lifecycle-interface": true,
    "use-pipe-transform-interface": true,
    "one-variable-per-declaration": false,
    "component-class-suffix": [true, "Page", "Component"],
    "directive-class-suffix": true,
    "directive-selector": [
      true,
      "attribute",
      "app",
      "camelCase"
    ],
    "component-selector": [
      true,
      "element",
      "app",
      "page",
      "kebab-case"
    ]
  }
}
`

**Comment by JoshuaKGoldberg** [comment]
Ah, looks like this is an issue from when you run `tslint-to-eslint-config` _twice_. If you delete your existing ESLint configuration file (by default, `.eslintrc.js`), it doesn't happen.

Thanks! This'll get fixed soon.

**Comment by HunSpeedi** [comment]
@JoshuaKGoldberg Yep, it is pretty much fixed it! Many thanks!!
